name: CI-Validate

on:
  push:
    branches:
      - main

# GitHub Actions Permissions use awsume role to access AWS resources securely
permissions:
  id-token: write
  contents: read

jobs:
  nomequalquer:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
          
      - run: npm install

      - name: Generate Tag
        id: generate_id
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: ${{ vars.DOCKERHUB_USERNAME }}/minha-app-node:${{ steps.generate_id.outputs.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/minha-app-node:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: everton-ci
          IMAGE_TAG: ${{ steps.generate_id.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Build Docker image
      #   run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/minha-app-node:${{ steps.generate_id.outputs.sha }} .

      # - name: Push Docker image
      #   run: docker push ${{ vars.DOCKERHUB_USERNAME }}/minha-app-node:${{ steps.generate_id.outputs.sha }}

      

     